Task_2_2_1
gikipil/OOP pull request #10
Opened 2023-05-24 05:17 UTC by gikipil

2023-06-16 12:14 UTC, shadrina commented on Task_2_2_1/src/main/java/org/example/Baker.java
> +    int experience;
Расскажешь мне про модификаторы области видимости и зачем они нужны

2023-06-16 12:14 UTC, shadrina commented on Task_2_2_1/src/main/java/org/example/Baker.java
> +                throw new RuntimeException(e);
Еще нужно будет рассказать про механизм выброса InterruptedException

2023-06-21 08:09 UTC, shadrina requested changes

2023-06-21 08:09 UTC, shadrina commented on Task_2_2_1/src/main/java/org/example/Baker.java
> +                        }
Вот это называется busy waiting. К экзамену надо обязательно понимать, что это такое и почему так нельзя.
Пока очередь пустая, ты не должен засыпать поток и заставлять его просыпаться каждые 10 миллисекунд. Это кушает ресурсы процессора, заставляет его каждые 10 миллисекунд восстанавливать контекст потока, который, вероятно, просто проверит условие и снова заснет.

Здесь надо погрузить поток в режим ожидания, а не сна. Это как раз цель всего механизма synchronized. 
Оно вообще работает?

2023-06-21 08:09 UTC, shadrina commented on Task_2_2_1/src/main/java/org/example/Baker.java
> +                        }
Ну да, работает оно так, что каждый повар по очереди блокирует монитор queue (термин монитор тоже надо хорошо знать) пока не появится что-то в очереди заказов. Хоть здесь и прокатило, в общем случае это верный путь к dead lock'у. Не надо блокировать монитор, отпускай его, когда он не нужен

2023-06-21 08:35 UTC, gikipil commented on Task_2_2_1/src/main/java/org/example/Baker.java
> +                        }
я заменил sleep на wait так правильнее ?

2023-06-21 09:48 UTC, shadrina commented on Task_2_2_1/src/main/java/org/example/Baker.java
> +                        }
А ты понимаешь, почему так правильнее?

2023-06-21 10:09 UTC, gikipil commented on Task_2_2_1/src/main/java/org/example/Baker.java
> +                        }
Wait вызывается для монитора а не для потока, когда он вызывается он снимает удерживающую блокировку, а sleep сохраняет ее. При его вызове поток переходит в неопределенное состояние пока кто-нибудь не вызовет notify таким образом его можно использовать для связи между потоками

2023-06-22 08:23 UTC, shadrina approved these changes

2023-06-22 08:24 UTC, merged