Task_1_3_1
gikipil/OOP pull request #5
Opened 2022-12-09 14:22 UTC by gikipil

2022-12-27 17:08 UTC, shadrina requested changes
Очень хорошие тесты, пока лучшие

2022-12-27 17:08 UTC, shadrina commented on Task_1_3_1/src/main/java/org/example/Find.java
> +        BufferedReader reader = new BufferedReader(
Слева пишем интерфейс (если таковой имеется), а не реализацию:
```
Reader reader = new BufferedReader(...
```

2022-12-27 17:08 UTC, shadrina commented on Task_1_3_1/src/main/java/org/example/Find.java
> +    public String open_file(String name) throws IOException {
В Java используется camelCase для всех наименований

2022-12-27 17:08 UTC, shadrina commented on Task_1_3_1/src/main/java/org/example/Find.java
> +        String file = "src/test/resources/" + name;
Из ресурсов надо читать правильно, используя `getResourcesAsStream`.

Вопрос на сдачу, почему так.

2022-12-27 17:08 UTC, shadrina commented on Task_1_3_1/src/main/java/org/example/Find.java
> +        }
Вот тут можно объединить два условия в одно через `||`

2022-12-29 16:45 UTC, gikipil commented on Task_1_3_1/src/main/java/org/example/Find.java
> +        String file = "src/test/resources/" + name;
getResourcesAsStream ищет путь к фалу - ресурсу, который может быть встроен в путь к классу в jar

2023-01-26 12:36 UTC, shadrina commented
Где правки?

2023-02-28 19:00 UTC, merged