Task_2_1_1
gikipil/OOP pull request #9
Opened 2023-02-28 19:03 UTC by gikipil

2023-03-12 19:02 UTC, shadrina requested changes

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +
Вот эти комменты можно не писать, reviewdog ругаться не будет

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +        Stack<Integer> num;
Почему решил использовать стек, а не обычный список / массив?

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +    boolean check = false;
Неприватный филд. Тут ниже есть сеттер, но без приватности этот сеттер смысла не имеет.
Если, конечно, нет какой-то хитро-мудрой логики с package private, которую тоже лучше не делать из-за ее неочевидности.

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +    PrimeNum root = this;
Аналогично хотелось бы соблюдения инкапсуляции, то есть здесь не хватает private.

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +            }
Меня смущает, что поток не останавливается даже если он уже нашел непростое число. В таком случае после нахождения поток будет делать лишнюю работу

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +        }
Тут лучше кинуть `IllegalStateException` или использовать аннотацию `@NotNull`. Не надо нормально реагировать на неправильный ввод

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +            return false;
Аналогично

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +     */
Лишние комменты лучше убирать

2023-03-12 19:02 UTC, shadrina commented on Task_2_1_1/src/test/java/PrimeNumTest.java
> +        Scanner input = new Scanner(new File("src/test/resources/1.txt"));
Мы в прошлом семестре проходили, что читать из ресурсов надо правильно, используя `getResourcesAsStream`. На сдаче задачи расскажи, пожалуйста, почему так

2023-03-15 12:22 UTC, gikipil commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +        Stack<Integer> num;
Просто нужна была очередь без необходимости позиционирования

2023-03-15 16:51 UTC, gikipil commented on Task_2_1_1/src/test/java/PrimeNumTest.java
> +        Scanner input = new Scanner(new File("src/test/resources/1.txt"));
я уже писал в задаче 1_3_1 то, что getResourcesAsStream ищет путь к фалу - ресурсу, который может быть встроен в путь к классу в jar

2023-03-20 08:33 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +        Stack<Integer> num;
У списка `java.util.List` нет позиционирования, и очередь это совсем не стек)

2023-03-21 08:16 UTC, shadrina requested changes
А что изменилось после последнего ревью?

2023-03-21 08:16 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +    PrimeNum root = this;
То же самое

2023-06-21 07:53 UTC, shadrina requested changes
Отдели, пожалуйста, считывание массива из input от непосредственно вычисления, чтобы мы измеряли время полезной работу потока.

2023-06-21 07:53 UTC, shadrina commented on Task_2_1_1/src/main/java/org/example/PrimeNum.java
> +        }
Проблема в том, что вот это попадает в измерение времени. На больших данных это дает значительный прирост и замыливает реальные значения

2023-06-21 13:20 UTC, gikipil commented
я уменьшил общую таблицу, тк очень долго приходиться ждать, не смотря на то что для одного теста время небольшое, в сумме если средние считать много времени уходит.

2023-06-22 08:25 UTC, shadrina approved these changes

2023-06-22 08:26 UTC, merged